- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: om
    url: http://54.226.177.177:8080
    user: om
  loop: "{{ folders }}"  

